/**
 * Module 4 + 5 — tenant payment flow with tax calculation.
 *
 * Wizard → payment-initiate (Edge Function) → processing screen driven by the
 * realtime + polling hybrid → payment-verify settles the sandbox payment and
 * runs the post-success pipeline (tax, receipt) → success page shows the
 * authoritative tax line and legal reference from the receipt.
 */

import { expect, test } from '@playwright/test';
import { IDS, RENT } from './support/fixtures';
import { installMockSupabase, realConsoleErrors } from './support/mockSupabase';

const RENT_LABEL = /850\s?000/;
const TAX_LABEL = /85\s?000/;

test.describe('Paiement du loyer (locataire)', () => {
  test('parcours complet : contrat → montant → Mobile Money → confirmation → reçu avec impôt', async ({ page }) => {
    const backend = await installMockSupabase(page, { role: 'locataire', settleAfterVerifyCalls: 2 });

    await page.goto('/locataire/paiements/nouveau');

    // Single active contract → the wizard skips straight to the amount step.
    await expect(page.getByRole('heading', { name: 'Nouveau paiement' })).toBeVisible();
    await expect(page.getByText('Montant et période')).toBeVisible();
    await expect(page.getByText('KIN-GOM-0042')).toBeVisible();

    // Estimated breakdown: rent + 10 % tax.
    await expect(page.getByText('Loyer brut')).toBeVisible();
    await expect(page.getByText(/Impôt \(10%\)/)).toBeVisible();
    await expect(page.getByText(RENT_LABEL).first()).toBeVisible();
    await expect(page.getByText(TAX_LABEL).first()).toBeVisible();

    await page.getByRole('button', { name: 'Continuer' }).click();

    // Method step — the catalogue comes from `payment_providers`.
    const methods = page.getByRole('radiogroup', { name: 'Méthode de paiement' });
    await expect(methods.getByRole('radio')).toHaveCount(5);
    await methods.getByRole('radio', { name: /Orange Money/ }).click();
    await expect(methods.getByRole('radio', { name: /Orange Money/ })).toHaveAttribute('aria-checked', 'true');

    // Phone is prefilled from the profile and must match +243 + 9 digits.
    const phone = page.getByLabel('Numéro Mobile Money');
    await expect(phone).toHaveValue('+243812345678');
    await expect(page.getByText('Mode test : aucun débit réel ne sera effectué.')).toBeVisible();

    await phone.fill('+24381');
    await expect(page.getByText('Format attendu : +243 suivi de 9 chiffres.')).toBeVisible();
    await expect(page.getByRole('button', { name: 'Continuer' })).toBeDisabled();
    await phone.fill('+243812345678');
    await page.getByRole('button', { name: 'Continuer' }).click();

    // Confirmation.
    await expect(page.getByRole('heading', { name: 'Confirmation' })).toBeVisible();
    await expect(page.getByText('Orange Money', { exact: true })).toBeVisible();
    await expect(page.getByText(/Montants estimés/)).toBeVisible();
    await page.getByRole('button', { name: /Confirmer le paiement de/ }).click();

    // Processing screen while the provider "confirms" (mock: settles on the 2nd verify).
    const processing = page.getByTestId('payment-processing');
    await expect(processing).toBeVisible();
    await expect(processing).toHaveAttribute('data-state', /processing|loading|pending/);
    // Once the provider has accepted (`processing`) the state machine forbids USER_CANCELLED.
    await expect(processing).toHaveAttribute('data-state', 'processing', { timeout: 15_000 });
    await expect(processing.getByRole('button', { name: 'Vérifier maintenant' })).toBeVisible();
    await expect(processing.getByRole('button', { name: 'Annuler le paiement' })).toHaveCount(0);

    // payment-initiate contract.
    await expect.poll(() => backend.callsTo('payment-initiate').length).toBe(1);
    const initiate = backend.callsTo('payment-initiate')[0]!;
    expect(initiate.body.contractId).toBe(IDS.contrat);
    expect(initiate.body.method).toBe('orange_money');
    expect(initiate.body.phone).toBe('+243812345678');
    expect(initiate.body.rentAmount).toBe(RENT);
    expect(Number(initiate.body.amount)).toBeGreaterThan(RENT);
    expect(String(initiate.body.idempotencyKey)).toMatch(/^pay-[0-9a-f]{8}-\d+-[0-9a-z]{8}$/i);
    expect(initiate.headers['authorization']).toMatch(/^Bearer /);

    // Polling fallback reaches the terminal state (realtime is muted by the mock).
    await expect.poll(() => backend.callsTo('payment-verify').length, { timeout: 20_000 }).toBeGreaterThanOrEqual(2);
    await expect(page).toHaveURL(/\/locataire\/paiements\/succes\?id=pay-e2e-/, { timeout: 20_000 });

    // Success page: receipt generated by the pipeline with the authoritative tax.
    const success = page.getByTestId('payment-success');
    await expect(success).toBeVisible();
    await expect(success.getByText(/enregistré avec succès/)).toBeVisible();
    await expect(success.getByText(/REC-2026-/)).toBeVisible({ timeout: 15_000 });
    await expect(success.getByText(/Impôt \(10%\)/)).toBeVisible();
    await expect(success.getByText(TAX_LABEL).first()).toBeVisible();
    await expect(success.getByText(/Base légale de l’impôt/)).toBeVisible();
    await expect(success.getByText(/Impôt sur les revenus locatifs/)).toBeVisible();
    await expect(success.getByRole('button', { name: 'Télécharger le reçu PDF' })).toBeEnabled();

    // The pipeline ran the tax engine exactly once for this payment.
    expect(backend.callsTo('tax-calculate (pipeline)')).toHaveLength(1);
    const payment = [...backend.payments.values()][0]!;
    expect(payment.state).toBe('succeeded');
    expect((payment.pipeline as Record<string, { status: string }>).tax.status).toBe('done');
    expect((payment.pipeline as Record<string, { status: string }>).receipt.status).toBe('done');

    expect(realConsoleErrors(backend)).toEqual([]);
  });

  test('échec opérateur : message français et bouton Réessayer', async ({ page }) => {
    const backend = await installMockSupabase(page, {
      role: 'locataire',
      settleAfterVerifyCalls: 1,
      outcome: 'failed',
      failureReason: 'insufficient_funds',
    });

    await page.goto('/locataire/paiements/nouveau');
    await page.getByRole('button', { name: 'Continuer' }).click();
    await page.getByRole('radio', { name: /M-Pesa/ }).click();
    await page.getByRole('button', { name: 'Continuer' }).click();
    await page.getByRole('button', { name: /Confirmer le paiement de/ }).click();

    await expect(page).toHaveURL(/\/locataire\/paiements\/echec\?id=pay-e2e-.*reason=insufficient_funds/, { timeout: 20_000 });
    const failed = page.getByTestId('payment-failed');
    await expect(failed).toHaveAttribute('data-reason', 'insufficient_funds');
    await expect(failed.getByRole('alert')).toHaveText('Solde insuffisant sur votre compte Mobile Money.');
    await expect(failed.getByRole('button', { name: 'Réessayer' })).toBeVisible();

    expect(backend.callsTo('payment-initiate')).toHaveLength(1);
    expect(backend.callsTo('tax-calculate (pipeline)')).toHaveLength(0);
    expect(realConsoleErrors(backend)).toEqual([]);
  });

  test('annulation en attente d’action passe par la machine à états (RPC cancel_own_payment)', async ({ page }) => {
    const backend = await installMockSupabase(page, { role: 'locataire', settleAfterVerifyCalls: 99, initialState: 'requires_action' });

    await page.goto('/locataire/paiements/nouveau');
    await page.getByRole('button', { name: 'Continuer' }).click();
    await page.getByRole('radio', { name: /Airtel Money/ }).click();
    await page.getByRole('button', { name: 'Continuer' }).click();
    await page.getByRole('button', { name: /Confirmer le paiement de/ }).click();

    // USSD prompt pending on the phone: the user may still back out.
    const processing = page.getByTestId('payment-processing');
    await expect(processing).toHaveAttribute('data-state', 'requires_action', { timeout: 15_000 });
    await expect(processing.getByText(/Confirmez le paiement sur votre téléphone/)).toBeVisible();
    await processing.getByRole('button', { name: 'Annuler le paiement' }).click();

    await expect.poll(() => backend.rpcCalls.filter((c) => c.name === 'cancel_own_payment').length).toBe(1);
    await expect(page).toHaveURL(/\/locataire\/paiements\/echec\?id=pay-e2e-.*reason=user_cancelled/, { timeout: 15_000 });
    await expect(page.getByTestId('payment-failed').getByRole('alert')).toHaveText('Vous avez annulé le paiement.');
    expect(realConsoleErrors(backend)).toEqual([]);
  });
});
