export {
  sendOTP,
  verifyOTP,
  signInWithPassword,
  signUpWithPhone,
  completeRegistration,
  uploadKycDocument,
  requestEmailVerification,
  updateProfile,
  fetchUserProfile,
  logout,
  refreshSession,
  resetPasswordByEmail,
  updatePassword,
} from '@/services/auth.service';
